Problem: Error when building Handcrafting Transactions docs (#476)
TypeError: Object of type 'bytes' is not JSON serializable

Solution: Use base58.b58encode(key).decode() which is a str,
instead of base58.b58encode(key) which is a bytes object